version: "3.9"
services:
  db:
    container_name: postgres_container
    image: postgres:15.1
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${USER}"
      POSTGRES_PASSWORD: "${PSWD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    restart: unless-stopped
    volumes:
      - /home/u1/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: ~/spbgo
      dockerfile: Dockerfile
    command: python3 main.py
    depends_on:
      - db
  frontend:
    build:
      context: /home/u1/SPBGo
      dockerfile: Front
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    expose:
      - '3000'
    ports:
      - 3000:3000
    command: npm run start
  nginx:
    build:
      dockerfile: Nginx
    depends_on:
      - db
      - backend
      - frontend
    ports:
      - "8080:80"
