version: "3.9"
services:
  db:
    container_name: postgres_container
    image: postgres:15.1
    environment:
      POSTGRES_DB: "spbgo"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "passforspb"
    restart: unless-stopped
    ports:
      - "5432:5432"
