version: "3.9"
services:
  db:
    container_name: postgres_container
    image: postgres:15.1
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${USER}"
      POSTGRES_PASSWORD: "${PSWD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    restart: unless-stopped
    volumes:
      - /home/u1/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
